=== auzpatwary37/matsim-models/src/test/resources/matsim-spec/laneDefinitions_v2.0.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
  MATSim wire-format schema for lane definitions, version 2.0 (laneDefinitions_v2.0).

  THIRD-PARTY SPECIFICATION MATERIAL; NOT re-licensed as Apache-2.0.
  Adapted from the published MATSim schema:
      https://matsim.org/files/dtd/laneDefinitions_v2.0.xsd
  Upstream: MATSim (matsim.org / github.com/matsim-org/matsim).
  Original editor, as credited in the published schema:
      Dominik Grether, VSP, Berlin Institute of Technology.
  This individual specification file carries no in-file license, and its upstream
  license has not been independently verified; do not treat it as Apache-2.0 (or as
  any other license).
  It is a data-format specification used for offline interoperability validation
  (test scope only). See THIRD_PARTY_NOTICES.md in the repository root.
-->
<xs:schema targetNamespace="http://www.matsim.org/files/dtd"
           xmlns="http://www.matsim.org/files/dtd"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xml:lang="en">

<!-- Editor: Dominik Grether, VSP, Berlin Institute of Technology -->
<!-- Description of the lanes to be used in
the simulation -->

<xs:include schemaLocation="matsimCommon.xsd"/>

<xs:element name="laneDefinitions">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="lanesToLinkAssignment" type="lanesToLinkAssignmentType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="lanesToLinkAssignmentType">
  <xs:sequence>
    <xs:element name="lane" type="laneType" minOccurs="1" maxOccurs="unbounded"></xs:element>
  </xs:sequence>
  <xs:attribute name="linkIdRef" type="matsimIdType"></xs:attribute>
</xs:complexType>

<xs:complexType name="laneType">
  <xs:complexContent>
    <xs:extension base="matsimObjectType">
      <xs:sequence>
        <xs:element name="leadsTo">
          <xs:complexType>
            <xs:choice>
              <xs:element name="toLink" type="idRefType" minOccurs="1" maxOccurs="unbounded"></xs:element>
              <xs:element name="toLane" type="idRefType" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:choice>
          </xs:complexType>
        </xs:element>
        <xs:element name="representedLanes" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="number" type="xs:double" use="optional" default="1">
              <xs:annotation>
                <xs:appinfo>
                  </xs:appinfo>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="capacity" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="vehiclesPerHour" type="xs:double" use="optional" default="3600">
              <xs:annotation>
                <xs:appinfo>
                  </xs:appinfo>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="startsAt" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="meterFromLinkEnd" type="xs:double" use="optional" default="45.0"></xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="alignment" type="xs:int"></xs:element>
        <xs:element name="attributes" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded"></xs:element>
            </xs:sequence> 
          </xs:complexType>
        </xs:element>
      </xs:sequence>    
    </xs:extension>
  </xs:complexContent>
</xs:complexType>

</xs:schema>

=== auzpatwary37/matsim-models/src/test/resources/fixtures/lanes.xml
<?xml version="1.0" encoding="UTF-8"?>
<laneDefinitions xmlns="http://www.matsim.org/files/dtd"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/laneDefinitions_v2.0.xsd">
    <lanesToLinkAssignment linkIdRef="l1">
        <lane id="l1_l0">
            <leadsTo>
                <toLink refId="l2"/>
            </leadsTo>
            <capacity vehiclesPerHour="1800.0"/>
            <startsAt meterFromLinkEnd="0.0"/>
            <alignment>0</alignment>
            <attributes>
                <attribute name="osm:lane.confidence" class="java.lang.String">present</attribute>
                <attribute name="lane-kind" class="java.lang.String">bus</attribute>
            </attributes>
        </lane>
        <lane id="l1_l1">
            <leadsTo>
                <toLane refId="l2_l0"/>
            </leadsTo>
            <capacity vehiclesPerHour="1800.0"/>
            <startsAt meterFromLinkEnd="45.0"/>
            <alignment>1</alignment>
            <attributes>
                <attribute name="lane-kind" class="java.lang.String">car</attribute>
            </attributes>
        </lane>
    </lanesToLinkAssignment>
    <lanesToLinkAssignment linkIdRef="l2">
        <lane id="l2_l0">
            <leadsTo>
                <toLink refId="l3"/>
            </leadsTo>
            <capacity vehiclesPerHour="900.0"/>
            <alignment>0</alignment>
            <attributes>
                <attribute name="lane-kind" class="java.lang.String">mixed</attribute>
            </attributes>
        </lane>
    </lanesToLinkAssignment>
</laneDefinitions>
