=== auzpatwary37/matsim-models/src/test/resources/matsim-spec/transitSchedule_v2.dtd
<!--
  Published MATSim wire-format DTD for transit schedules, version 2.
  Retrieved verbatim from https://matsim.org/files/dtd/transitSchedule_v2.dtd
  and vendored here for OFFLINE INTEROPERABILITY VALIDATION ONLY (test scope).
  It is a data-format specification, used the same way the GTFS spec is used.
-->
<!ELEMENT transitSchedule  (attributes?,transitStops?,minimalTransferTimes?,transitLine*)>


<!ELEMENT attributes    (attribute*)>

<!ELEMENT attribute       (#PCDATA)>
<!ATTLIST attribute
          name             CDATA #REQUIRED
          class            CDATA #REQUIRED>

<!ELEMENT transitStops     (stopFacility)*>

<!ELEMENT stopFacility     (attributes?)>
<!ATTLIST stopFacility
          id               CDATA   #REQUIRED
          x                CDATA   #REQUIRED
          y                CDATA   #REQUIRED
          z                CDATA   #IMPLIED
          linkRefId        CDATA   #IMPLIED
          name             CDATA   #IMPLIED
          stopAreaId       CDATA   #IMPLIED
          isBlocking       (true|false)  "false">

<!ELEMENT minimalTransferTimes    (relation*)>

<!ELEMENT relation         EMPTY>
<!ATTLIST relation
          fromStop         CDATA   #REQUIRED
          toStop           CDATA   #REQUIRED
          transferTime     CDATA   #REQUIRED>
<!-- relations specify the transferTime in seconds between two stop facilities in the specified direction -->

<!ELEMENT transitLine      (attributes?,transitRoute*)>
<!ATTLIST transitLine
          id               CDATA   #REQUIRED
          name             CDATA   #IMPLIED>

<!ELEMENT transitRoute     (attributes?,description?,transportMode,routeProfile,route?,departures)>
<!ATTLIST transitRoute
          id               CDATA   #REQUIRED>
<!-- transitRoute.id must be unique within a transitLine only. -->

<!ELEMENT description      (#PCDATA)>

<!ELEMENT transportMode    (#PCDATA)>
<!-- describes the mode of which vehicles are that serve that line/route -->

<!ELEMENT routeProfile     (stop)*>

<!ELEMENT stop             EMPTY>
<!ATTLIST stop
          refId            CDATA   #REQUIRED
          departureOffset  CDATA   #IMPLIED
          arrivalOffset    CDATA   #IMPLIED
          minimumStopDuration CDATA   #IMPLIED
          allowBoarding    (true|false)  "true"
          allowAlighting   (true|false)  "true"
          awaitDeparture   (true|false)  "false">
<!--
 * stop.departureOffset is required for all stops but the last.
   The offsets are to be added to the departure times of the single
   departures listed in the transitRoute.
 * stop.refId are id-references to facilities. -->

<!ELEMENT route            (link)*>

<!ELEMENT link             EMPTY>
<!ATTLIST link
          refId            CDATA   #REQUIRED>

<!ELEMENT departures       (departure*)>
<!-- the single departures along that transitRoute -->

<!ELEMENT departure        (attributes?,chainedDeparture*)>
<!ATTLIST departure
          id               CDATA   #REQUIRED
          departureTime    CDATA   #REQUIRED
          vehicleRefId     CDATA   #IMPLIED>
<!-- the departure.id must be unique within a transitLine only -->

<!ELEMENT chainedDeparture EMPTY>
<!ATTLIST chainedDeparture
          toDeparture      CDATA   #REQUIRED
          toTransitLine    CDATA   #IMPLIED
          toTransitRoute   CDATA   #IMPLIED>

=== auzpatwary37/matsim-models/src/test/resources/matsim-spec/transitSchedule-current-v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transitSchedule SYSTEM "transitSchedule_v2.dtd">
<!--
  Interoperability fixture: a transit schedule in the current MATSim
  transitSchedule v2 wire format, declared against the published DTD
  transitSchedule_v2.dtd vendored in this directory. Hand-written strictly
  from the DTD content model; contains no MATSim or external-converter code.
-->
<transitSchedule>
  <transitStops>
    <stopFacility id="stop-1" x="0.0" y="0.0" linkRefId="link-1" name="Main" stopAreaId="area-1" isBlocking="false"/>
    <stopFacility id="stop-2" x="100.0" y="0.0" linkRefId="link-2" stopAreaId="area-1" isBlocking="false"/>
    <stopFacility id="stop-3" x="200.0" y="0.0" linkRefId="link-3" isBlocking="false"/>
  </transitStops>
  <transitLine id="line-1">
    <transitRoute id="route-1">
      <description>Main line</description>
      <transportMode>bus</transportMode>
      <routeProfile>
        <stop refId="stop-1" arrivalOffset="0:00:00" departureOffset="0:00:30"/>
        <stop refId="stop-2" arrivalOffset="0:01:00" departureOffset="0:01:30"/>
        <stop refId="stop-3" arrivalOffset="0:02:00" departureOffset="0:02:30" awaitDeparture="false"/>
      </routeProfile>
      <route>
        <link refId="link-1"/>
        <link refId="link-2"/>
        <link refId="link-3"/>
      </route>
      <departures>
        <departure id="dep-1" departureTime="8:30:00" vehicleRefId="bus-1"/>
      </departures>
    </transitRoute>
  </transitLine>
</transitSchedule>
