=== auzpatwary37/matsim-models/src/test/resources/matsim-spec/vehicleDefinitions_v2.0.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
  Published MATSim wire-format schema for vehicle definitions, version 2.0.
  Retrieved verbatim from https://matsim.org/files/dtd/vehicleDefinitions_v2.0.xsd
  and vendored here for OFFLINE INTEROPERABILITY VALIDATION ONLY (test scope).
  It is a data-format specification, used the same way the GTFS spec is used.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.matsim.org/files/dtd" xmlns="http://www.matsim.org/files/dtd"
           elementFormDefault="qualified"
           xml:lang="en">
    <xs:include schemaLocation="http://www.matsim.org/files/dtd/matsimCommon.xsd"/>
    <xs:include schemaLocation="http://www.matsim.org/files/dtd/vehicleDefinitionsEnumTypes.xsd"/>

    <xs:element name="vehicleDefinitions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehicleType" type="vehicleTypeType" maxOccurs="unbounded"/>
                <xs:element name="vehicle" type="vehicleDefType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="vehicleTypeType">
        <xs:complexContent>
            <xs:extension base="matsimObjectType">
                <xs:sequence>
                    <xs:element name="attributes" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="description" type="xs:string" minOccurs="0"/>
                    <xs:element name="capacity" type="capacityType" minOccurs="0"/>
                    <xs:element name="length" minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name="meter" type="xs:decimal" default="7.5"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="width" minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name="meter" type="xs:decimal" default="1"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="maximumVelocity" minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name="meterPerSecond" type="xs:double" default="INF"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="engineInformation" type="engineInformationType" minOccurs="0"/>
                    <xs:element name="costInformation" type="costInformationType" minOccurs="0"/>
                    <xs:element name="passengerCarEquivalents" minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name="pce" type="xs:decimal" default="1.0"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="networkMode" minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name="networkMode" type="xs:string"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="flowEfficiencyFactor" minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name="factor" type="xs:decimal" default="1.0"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="capacityType">
        <xs:sequence>
            <xs:element name="attributes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="seats" type="xs:nonNegativeInteger"/>
        <xs:attribute name="standingRoomInPersons" type="xs:nonNegativeInteger"/>
        <xs:attribute name="volumeInCubicMeters" type="xs:double"/>
        <xs:attribute name="weightInTons" type="xs:double"/>
        <xs:attribute name="other" type="xs:double"/>
    </xs:complexType>

    <xs:complexType name="engineInformationType">
        <xs:sequence>
            <xs:element name="attributes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="costInformationType">
        <xs:sequence>
            <xs:element name="attributes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="fixedCostsPerDay" type="xs:double"/>
        <xs:attribute name="costsPerMeter" type="xs:double"/>
        <xs:attribute name="costsPerSecond" type="xs:double"/>
    </xs:complexType>


    <xs:complexType name="vehicleDefType">
        <xs:annotation>
            <xs:documentation/>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="matsimObjectType">
                <xs:sequence>
                    <xs:element name="attributes" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
                <xs:attribute name="type" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== auzpatwary37/matsim-models/src/test/resources/matsim-spec/vehicleDefinitions-current-v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Interoperability fixture: a vehicle definitions file in the CURRENT MATSim
  vehicleDefinitions v2.0 wire format. Authored by hand strictly from the
  published v2.0 schema (matsim-spec/vehicleDefinitions_v2.0.xsd) and the
  documented vehicle-type attribute conventions; it contains no MATSim or
  external-converter code. Used to prove the reader ingests current-format input.
-->
<vehicleDefinitions xmlns="http://www.matsim.org/files/dtd"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/vehicleDefinitions_v2.0.xsd">
    <vehicleType id="Bus">
        <attributes>
            <attribute name="accessTimeInSecondsPerPerson" class="java.lang.Double">0.5</attribute>
            <attribute name="doorOperationMode" class="java.lang.String">serial</attribute>
            <attribute name="egressTimeInSecondsPerPerson" class="java.lang.Double">1.5</attribute>
        </attributes>
        <capacity seats="40" standingRoomInPersons="60"/>
        <length meter="12.0"/>
        <width meter="2.5"/>
        <passengerCarEquivalents pce="22.0"/>
    </vehicleType>
    <vehicleType id="car">
        <capacity seats="4"/>
        <maximumVelocity meterPerSecond="16.67"/>
        <passengerCarEquivalents pce="1.0"/>
    </vehicleType>
    <vehicle id="bus-1" type="Bus"/>
    <vehicle id="bus-2" type="Bus"/>
    <vehicle id="car-1" type="car"/>
</vehicleDefinitions>
